### ISSUE TITLE
The implementation for IPI on X2Apic available platforms seems to be wrong

### ISSUE THREAD

**Issue by hiroki-chen** [rcore-os/apic-rs#3]
Thank you for making this crate that makes OS development easier!

However, I recently used this crate to implement IPI on X2Apic available platforms and noticed that `lib.rs` gives a default implementation of the `LocalApic` trait:

```rust
/// Send an IPI to a remote CPU
    fn send_ipi(&mut self, apic_id: u8, int_id: u8) {
        self.set_icr((apic_id as u64) << 56 | int_id as u64);
    }
```

Although it works for XApic, the mechanism for X2Apic differs, but the authors do not provide an implementation for that, which should be

```rust
    fn send_ipi(&mut self, apic_id: u8, int_id: u8) {
        // should be 32 instead of 56 :)
        self.set_icr((apic_id as u64) << 32 | int_id as u64 | 1 << 14);
    }
```

FYI, Intel's manual says, "The lower 32 bits of ICR in x2APIC mode are identical to the lower half of the ICR in xAPIC mode, except bit 12 (Delivery Status) is not used since it is not needed in X2APIC mode. The destination ID field is expanded to 32 bits in x2APIC mode."

**Comment by wangrunji0408** [comment]
Thanks for pointing it out! I recall that the code was copied from somewhere and x2APIC was not well tested.
If you are using this crate, feel free to send PR to fix this issue. As you can see, this crate has not been maintained for a while. You may use [x2apic](https://github.com/kwzhao/x2apic-rs) or [x86::apic](https://docs.rs/x86/0.52.0/x86/apic/index.html) as alternative.

**Comment by hiroki-chen** [comment]
Hi Runji, I made a PR that fixes this issue. Let me know if you have any question or concern!
